void displaySolarSystem();
float equationOfCircle(float centerx,float centery,float x,float y,float radius);
void drawMercury(GLfloat x, GLfloat y, GLfloat radius);
void drawVenus(GLfloat x, GLfloat y, GLfloat radius);
void drawEarth(GLfloat x, GLfloat y, GLfloat radius);
void drawMars(GLfloat x, GLfloat y, GLfloat radius);
void drawJupitor(GLfloat x, GLfloat y, GLfloat radius);
void drawSaturn(GLfloat x, GLfloat y, GLfloat radius);
void drawUranus(GLfloat x, GLfloat y, GLfloat radius);
void drawNeptune(GLfloat x, GLfloat y, GLfloat radius);
void drawPluto(GLfloat x, GLfloat y, GLfloat radius);
void drawSun(GLfloat x, GLfloat y, GLfloat radius);
void drawFilledCircle(GLfloat x, GLfloat y, GLfloat radius);
int playMusic();